声波电动牙刷: 
    heighlights: [高效清洁, 减少手动压力, 定时提醒, 智能模式调节, 无线充电, 噪音低]
    image_path: "http://localhost:8000/files/images/elec_toothblush.png"
    instruction: "http://localhost:8000/files/instructions/elec_toothblush.md"
    departure_place: "汕头"
    delivery_company: "顺丰"
    selling_price: 99.9
    amount: 10000
    upload_date: "1722944846"
    sales_doc: "声波电动牙刷"
    digital_human_video: "666"
    product_id: 1
    product_class: "电子"


唇膏: 
    heighlights: [丰富色号, 滋润保湿, 显色度高, 持久不脱色, 易于涂抹, 便携包装]
    image_path: "http://localhost:8000/files/images/lip_stick.png"
    instruction: "http://localhost:8000/files/instructions/lip_stick.md"
    departure_place: "宁波"
    delivery_company: "圆通"
    selling_price: 399.8
    amount: 1068
    upload_date: "1722944859"
    sales_doc: "唇膏"
    digital_human_video: "666"
    product_id: 2
    product_class: "美妆"


本草精华洗发露: 
    heighlights: [温和配方, 深层清洁, 滋养头皮, 丰富泡沫, 易冲洗, 适合各种发质]
    image_path: "http://localhost:8000/files/images/shampoo.png"
    instruction: "http://localhost:8000/files/instructions/shampoo.md"
    departure_place: "广州"
    delivery_company: "申通"
    selling_price: 60.0
    amount: 106999
    upload_date: "1722944865"
    sales_doc: "本草精华洗发露"
    digital_human_video: "666"
    product_id: 3
    product_class: "日用品"


光感润颜面膜: 
    heighlights: [密集滋养, 深层补水, 急救修复, 快速见效, 定期护理, 多种类型选择]
    image_path: "http://localhost:8000/files/images/mask.png"
    instruction: "http://localhost:8000/files/instructions/mask.md"
    departure_place: "广州"
    delivery_company: "韵达"
    selling_price: 299.0
    amount: 68441
    upload_date: "1722944865"
    sales_doc: "光感润颜面膜"
    digital_human_video: "666"
    product_id: 4
    product_class: "美妆"


薰衣草淡香氛: 
    heighlights: [浪漫优雅, 花香调为主, 情感表达, 适合各种年龄, 瓶身设计精致, 提升女性魅力]
    image_path: "http://localhost:8000/files/images/perfume.png"
    instruction: "http://localhost:8000/files/instructions/perfume.md"
    departure_place: "广州"
    delivery_company: "韵达"
    selling_price: 499.0
    amount: 681321
    upload_date: "1722944865"
    sales_doc: "薰衣草淡香氛"
    digital_human_video: "666"
    product_id: 5
    product_class: "家居用品"


墨水钢笔: 
    heighlights: [耐用性, 可书写性, 不同颜色和类型, 轻便设计, 环保材料, 易于携带]
    image_path: "http://localhost:8000/files/images/pen.png"
    instruction: "http://localhost:8000/files/instructions/pen.md"
    departure_place: "宁波"
    delivery_company: "圆通"
    selling_price: 36.8
    amount: 681684
    upload_date: "1722944877"
    sales_doc: "墨水钢笔"
    digital_human_video: "666"
    product_id: 6
    product_class: "文具"


瑜伽垫: 
    heighlights: [防滑材质, 吸湿排汗, 厚度适中, 耐用易清洁, 各种瑜伽动作适用, 轻巧便携]
    image_path: "http://localhost:8000/files/images/yoga_mat.png"
    instruction: "http://localhost:8000/files/instructions/yoga_mat.md"
    departure_place: "汕头"
    delivery_company: "圆通"
    selling_price: 16.8
    amount: 987913
    upload_date: "1722944883"
    sales_doc: "瑜伽垫"
    digital_human_video: "666"
    product_id: 7
    product_class: "运动"


速干运动裤: 
    heighlights: [快干, 伸缩自如, 吸湿排汗, 防风保暖, 高腰设计, 多口袋实用]
    image_path: "http://localhost:8000/files/images/pants.png"
    instruction: "http://localhost:8000/files/instructions/pants.md"
    departure_place: "广州"
    delivery_company: "圆通"
    selling_price: 66.9
    amount: 12435
    upload_date: "1722944888"
    sales_doc: "速干运动裤"
    digital_human_video: "666"
    product_id: 8
    product_class: "衣服"


不粘煎炒锅: 
    heighlights: [不粘涂层, 耐磨耐用, 导热快, 易清洗, 多种烹饪方式, 设计人性化]
    image_path: "http://localhost:8000/files/images/wok.png"
    instruction: "http://localhost:8000/files/instructions/wok.md"
    departure_place: "武汉"
    delivery_company: "京东"
    selling_price: 168.6
    amount: 67423
    upload_date: "1722944894"
    sales_doc: "不粘煎炒锅"
    digital_human_video: "666"
    product_id: 9
    product_class: "厨具"


14英寸平板电脑: 
    heighlights: [轻薄, 触控操作, 电池续航好, 移动办公便利, 娱乐性强, 适合儿童学习]
    image_path: "http://localhost:8000/files/images/pad.png"
    instruction: "http://localhost:8000/files/instructions/pad.md"
    departure_place: "广州"
    delivery_company: "京东"
    selling_price: 1999.99
    amount: 932
    upload_date: "1722944900"
    sales_doc: "14英寸平板电脑"
    digital_human_video: "666"
    product_id: 10
    product_class: "电子"


65英寸OLED电视: 
    heighlights: [色彩鲜艳, 对比度极高, 响应速度快, 无背光眩光, 厚度较薄, 自发光无需额外照明]
    image_path: "http://localhost:8000/files/images/oled_tv.png"
    instruction: "http://localhost:8000/files/instructions/oled_tv.md"
    departure_place: "广州"
    delivery_company: "京东"
    selling_price: 12999.99
    amount: 68731
    upload_date: "1722944905"
    sales_doc: "65英寸OLED电视"
    digital_human_video: "666"
    product_id: 11
    product_class: "家电"


进口和牛羽下肉: 
    heighlights: [富含铁质, 营养价值高, 肌肉纤维好, 红白相间纹理, 适合烧烤炖煮, 草食动物来源]
    image_path: "http://localhost:8000/files/images/beef.png"
    instruction: "http://localhost:8000/files/instructions/beef.md"
    departure_place: "广州"
    delivery_company: "顺丰"
    selling_price: 99.68
    amount: 96836
    upload_date: "1722944912"
    sales_doc: "进口和牛羽下肉"
    digital_human_video: "666"
    product_id: 12
    product_class: "食品"
