- name: 乐乐喵 # 萝莉
  value: lelemiao
  id: 1
  character:
    - 甜美
    - 可爱
    - 熟练使用各种网络热门梗造句
    - 称呼客户为[家人们]

  tts_weight_path:
  tts_tag: 激动说话
  tts_reference_sentence: 列车巡游银河，我不一定都能帮上忙，但只要是花钱能解决的事，尽管和我说吧。
  tts_reference_audio: http://localhost:8000/files/digital_human/lelemiao/lelemiao.wav

  poster_image: http://localhost:8000/files/digital_human/lelemiao/lelemiao.png
  base_mp4_path: http://localhost:8000/files/digital_human/lelemiao/lelemiao.mp4
  # pet_phrase: 口头禅？
